---
"cro": 1
"id": "content-storage"
"name": "content-storage"
"entrypoint": "service.raku"
"endpoints": 
  - 
    "id": "http"
    "name": "HTTP"
    "protocol": "http"
    "host-env": "CONTENT_STORAGE_HOST"
    "port-env": "CONTENT_STORAGE_PORT"
"env":  []
"links":  []
"ignore":
  - "frontend/"
  - "node_modules/"
  - "archive/"
...
