version: '3.7'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    expose:
      - "5432"
    restart: always

  web:
    build: .
    expose:
      - "20000"
    depends_on:
      - database
    links:
      - database:database
    environment:
      - CONTENT_STORAGE_DB_CONN_INFO=postgresql://test:test@database:5432/test
    restart: always


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web
    restart: always


